steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-northeast3-docker.pkg.dev/exemplary-datum-362307/fatclinic/fatclinic-was', '.' ]
images:
- 'asia-northeast3-docker.pkg.dev/exemplary-datum-362307/fatclinic/fatclinic-was'
