apiVersion: apps/v1
kind: Deployment
metadata:
  name: fatclinic-was-deployment
  labels:
    app: fatclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fatclinic
  template:
    metadata:
      labels:
        app: fatclinic
        tier: was
    spec:
      containers:
      - name: fatclinic-container
        image: asia-northeast3-docker.pkg.dev/exemplary-datum-362307/fatclinic/fatclinic-was
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 250Mi
            cpu: 100m
